/*
 * Copyright (C) 2011 leclaire
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * BasePrototypePanelUI.java
 *
 * Created on 12 mai 2011, 15:36:34
 */
package org.openmole.ide.plugin.prototype.base;

import org.openmole.ide.core.properties.PanelUI;
import org.openmole.ide.core.properties.PanelUIData;

/**
 *
 * @author mathieu
 */
public class BasePrototypePanelUI extends PanelUI {

    BasePrototypePanelUIData panelData;

    /** Creates new form BasePrototypePanelUI */
    public BasePrototypePanelUI(BasePrototypePanelUIData panelData) {
        super(panelData);
        initComponents();
        typeClassComboBox.addItem("Integer");
        typeClassComboBox.addItem("Double");
        typeClassComboBox.addItem("File");
        typeClassComboBox.addItem("String");
        typeClassComboBox.addItem("BigInteger");
        typeClassComboBox.addItem("BigDecimal");
    }

    public void saveContent() {
        System.out.println("in saveContent  BasePrototypePanelUI" + typeClassComboBox);
        System.out.println("in saveContent  BasePrototypePanelUI" + typeClassComboBox.getSelectedItem());
        System.out.println("in saveContent  BasePrototypePanelUI" + (String) typeClassComboBox.getSelectedItem());
        panelData.simpleTypeString_$eq((String) typeClassComboBox.getSelectedItem());
    }

    public void loadContent() {
        System.out.println("in loadontent BasePrototypePanelUI " + typeClassComboBox);
        System.out.println("in loadontent BasePrototypePanelUI " + panelData.simpleTypeString());
        if (panelData.simpleTypeString() != "") typeClassComboBox.setSelectedItem(panelData.simpleTypeString());
        else typeClassComboBox.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeClassComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(BasePrototypePanelUI.class, "BasePrototypePanelUI.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(typeClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(typeClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox typeClassComboBox;
    // End of variables declaration//GEN-END:variables
}
