/*
 *
 *  Copyright (c) 2007, 2009, Cemagref
 *
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation; either version 3 of
 *  the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public
 *  License along with this program; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
 *  MA  02110-1301  USA
 */
package org.simexplorer.core.workflow.methods.r;

import javax.swing.SpinnerNumberModel;
import org.simexplorer.core.workflow.methods.DomainEditorPanel;

// TODO
class RFastMethod {

    Object getSamplingNumber() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    void setSamplingNumber(int intValue) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

}

public class RFastMethodPanel extends DomainEditorPanel<RFastMethod> {

    public RFastMethodPanel() {
        super(RFastMethod.class);
        initComponents();
    }

    @Override
    public void setObjectEdited(RFastMethod method) {
        super.setObjectEdited(method);
        samplingNumberSpinner.setValue(getObjectEdited().getSamplingNumber());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        samplingNumberSpinner = new javax.swing.JSpinner();

        jLabel1.setText("Number of sampling");

        samplingNumberSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                samplingNumberStateChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(samplingNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(samplingNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void samplingNumberStateChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_samplingNumberStateChange
        getObjectEdited().setSamplingNumber(((SpinnerNumberModel) samplingNumberSpinner.getModel()).getNumber().intValue());
    }//GEN-LAST:event_samplingNumberStateChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner samplingNumberSpinner;
    // End of variables declaration//GEN-END:variables

    @Override
    public Class getType() {
        return Double.class;
    }

}
