#!/bin/sh

CURDIR=$PWD
LOCATION=`dirname $0`

cd $LOCATION

MEM="1G"

FLAG=""

JVMVERSION=`java -version 2>&1 | tail -1 -`

case "$JVMVERSION" in
  *64-Bit*) FLAG="-XX:+UseCompressedOops";;
esac

rm -Rf ./configuration/org*
rm ./configuration/*.log
java -ea -Xmx${MEM} -Dosgi.classloader.singleThreadLoads=true $FLAG -XX:MaxPermSize=128M -XX:+UseParallelGC \
     -jar ./plugins/org.eclipse.equinox.launcher.jar \
     -p ./openmole-plugins -g ./openmole-plugins-gui "$@"
#cat $LOCATION/configuration/*.log

cd $CURDIR

