/*
 * Copyright (C) 2011 <mathieu.leclaire at openmole.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GliteEnvironmentPanelUI.java
 *
 * Created on 10 juin 2011, 10:34:04
 */
package org.openmole.ide.plugin.environment.glite;

import org.openmole.ide.core.properties.IEnvironmentPanelUI;
import org.openmole.ide.core.properties.IEnvironmentDataUI;
import javax.swing.JPanel;

/**
 *
 * @author mathieu
 */
public class GliteEnvironmentPanelUI extends JPanel  implements IEnvironmentPanelUI {

    /** Creates new form GliteEnvironmentPanelUI */
    public GliteEnvironmentPanelUI(GliteEnvironmentDataUI pud) {
        initComponents();
        voTextField.setText(pud.vo());
        vomsTextField.setText(pud.voms());
        bdiiTextField.setText(pud.bdii());
    }

    public JPanel peer() {return this;}
    public IEnvironmentDataUI saveContent(String name) {
        return new GliteEnvironmentDataUI(name,
                voTextField.getText(),
                vomsTextField.getText(),
                bdiiTextField.getText());
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        voTextField = new javax.swing.JTextField();
        vomsTextField = new javax.swing.JTextField();
        bdiiTextField = new javax.swing.JTextField();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(GliteEnvironmentPanelUI.class, "GliteEnvironmentPanelUI.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(GliteEnvironmentPanelUI.class, "GliteEnvironmentPanelUI.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(GliteEnvironmentPanelUI.class, "GliteEnvironmentPanelUI.jLabel3.text")); // NOI18N

        voTextField.setText(org.openide.util.NbBundle.getMessage(GliteEnvironmentPanelUI.class, "GliteEnvironmentPanelUI.voTextField.text")); // NOI18N
        voTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voTextFieldActionPerformed(evt);
            }
        });

        vomsTextField.setText(org.openide.util.NbBundle.getMessage(GliteEnvironmentPanelUI.class, "GliteEnvironmentPanelUI.vomsTextField.text")); // NOI18N

        bdiiTextField.setText(org.openide.util.NbBundle.getMessage(GliteEnvironmentPanelUI.class, "GliteEnvironmentPanelUI.bdiiTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(voTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bdiiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(vomsTextField))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(voTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vomsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdiiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voTextFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bdiiTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField voTextField;
    private javax.swing.JTextField vomsTextField;
    // End of variables declaration//GEN-END:variables
}
