/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MetaDataPanel.java
 *
 * Created on 29 avr. 2009, 00:52:54
 */

package org.simexplorer.ide.ui.wizards.newApplication;

import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import org.openide.util.NbBundle;

/**
 *
 * @author thierry
 */
public class MetaDataPanel extends javax.swing.JPanel {

    /** Creates new form MetaDataPanel */
    public MetaDataPanel() {
        messageLabel=new JLabel();

        initComponents();
        this.setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        metadataPanel=new JPanel();
        metadataPanel.setLayout(new BoxLayout(metadataPanel, BoxLayout.PAGE_AXIS));
        metadataPanel.setBorder(BorderFactory.createTitledBorder(NbBundle.getMessage(MetaDataPanel.class, "MetaDataPanel.jScrollPane1.border.title"))); // NOI18N

        metadataPanel.add(new OneMetadataPanel("description", "", true, false));
        metadataPanel.add(new OneMetadataPanel("author", "", false, false));
        metadataPanel.add(new OneMetadataPanel("references", "", false, false));
            metadataPanel.setPreferredSize(new Dimension(500, 200));

        jScrollPane1=new JScrollPane();
        jScrollPane1.setViewportView(metadataPanel);
//            this.add();

        //TODO mettre les popup dans une classe a part
        // Création d'un JPopupMenu
        final JPopupMenu removeMetadataPopupMenu = new JPopupMenu();
        JMenuItem remove = new JMenuItem("remove");
        remove.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if (e.getActionCommand().equals("remove")) {
                    // custon remove of component under the mouse (with the contains(Point) method it's not working espected
                    Point posDragedElt = MouseInfo.getPointerInfo().getLocation();
                    for (int i = 3; i <
                            ((MetaDataPanel)metadataPanel).getPanel().getComponentCount(); i++) {
                        Point p = ((MetaDataPanel)metadataPanel).getPanel().getComponent(i).getLocationOnScreen();
                        if ((p.x < posDragedElt.x) &&
                                (p.x +
                                ((MetaDataPanel)metadataPanel).getPanel().getComponent(i).getWidth() >
                                posDragedElt.x)) {
                            if ((p.y < posDragedElt.y) &&
                                    (p.y +
                                    ((MetaDataPanel)metadataPanel).getPanel().getComponent(i).getHeight() >
                                    posDragedElt.y)) {
                                ((MetaDataPanel)metadataPanel).getPanel().remove(i);
                                ((MetaDataPanel)metadataPanel).getPanel().revalidate();
                                ((MetaDataPanel)metadataPanel).getPanel().repaint();
                            }
                        }
                    }
                }
            }
        });
        removeMetadataPopupMenu.add(remove);
/*        jScrollPane1.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                // clic on the right button
                if (e.getButton() == MouseEvent.BUTTON3) {
                    removeMetadataPopupMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
*/
        this.revalidate();

    }

    public JPanel getPanel() {
        return metadataPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {



        jScrollPane1 = new JScrollPane();
        metadataPanel = new JPanel();
        jButton2 = new JButton();

        messageLabel.setText(NbBundle.getMessage(MetaDataPanel.class, "MetaDataPanel.messageLabel.text")); // NOI18N
        jScrollPane1.setBorder(BorderFactory.createTitledBorder(NbBundle.getMessage(MetaDataPanel.class, "MetaDataPanel.jScrollPane1.border.title"))); // NOI18N
        metadataPanel.setBorder(null);
        metadataPanel.setLayout(new BoxLayout(metadataPanel, BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(metadataPanel);

        jButton2.setText(NbBundle.getMessage(MetaDataPanel.class, "MetaDataPanel.jButton2.text")); // NOI18N
        jButton2.setToolTipText(NbBundle.getMessage(MetaDataPanel.class, "MetaDataPanel.jButton2.toolTipText")); // NOI18N
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2addActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(messageLabel, GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 208, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(messageLabel, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2addActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2addActionPerformed
        metadataPanel.add(
                new OneMetadataPanel("", "", false, true));
        this.revalidate();
}//GEN-LAST:event_jButton2addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton2;
    private JScrollPane jScrollPane1;
    private JLabel messageLabel;
    private JPanel metadataPanel;
    // End of variables declaration//GEN-END:variables

}
