/*
 *  Copyright © 2009, Cemagref
 *
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 3 of
 *  the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public
 *  License along with this program; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
 *  MA  02110-1301  USA
 */
package org.simexplorer.ide.ui.wizards.newApplication;

import java.awt.Component;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import org.simexplorer.core.workflow.model.metada.Metadata;
import org.simexplorer.ui.tools.SimpleWizard;

/**
 *
 * @author thierry
 */
public class NewApplicationPanel extends SimpleWizard {

    /** Creates new form NewApplicationPanel */
    public NewApplicationPanel() {
        initComponents();
        jPanelAdditionalMetadata.add(new OneMetadataPanel("description", "", true, false));
        jPanelAdditionalMetadata.add(new OneMetadataPanel("author", "", false, false));
        jPanelAdditionalMetadata.add(new OneMetadataPanel("references", "", false, false));

        jTextFieldApplicationName.setName("ApplicationName");

        // Création d'un JPopupMenu
        final JPopupMenu removeMetadataPopupMenu = new JPopupMenu();
        JMenuItem remove = new JMenuItem("remove");
        remove.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if (e.getActionCommand().equals("remove")) {
                    // custon remove of component under the mouse (with the contains(Point) method it's not working espected
                    Point posDragedElt = MouseInfo.getPointerInfo().getLocation();
                    for (int i = 3; i <
                            jPanelAdditionalMetadata.getComponentCount(); i++) {
                        Point p = jPanelAdditionalMetadata.getComponent(i).getLocationOnScreen();
                        if ((p.x < posDragedElt.x) &&
                                (p.x +
                                jPanelAdditionalMetadata.getComponent(i).getWidth() >
                                posDragedElt.x)) {
                            if ((p.y < posDragedElt.y) &&
                                    (p.y +
                                    jPanelAdditionalMetadata.getComponent(i).getHeight() >
                                    posDragedElt.y)) {
                                jPanelAdditionalMetadata.remove(i);
                                jPanelAdditionalMetadata.revalidate();
                                jPanelAdditionalMetadata.repaint();
                            }
                        }
                    }
                }
            }
        });
        removeMetadataPopupMenu.add(remove);
        jScrollPane1.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                // clic on the right button
                if (e.getButton() == MouseEvent.BUTTON3) {
                    removeMetadataPopupMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });

    }

    public String getApplicationName() {
        return jTextFieldApplicationName.getText();
    }

    public Metadata getMetadata() {
        Metadata metadata = new Metadata();
        for (Component co : jPanelAdditionalMetadata.getComponents()) {
            metadata.set(((OneMetadataPanel) co).getMetadataKey(), ((OneMetadataPanel) co).getMetadataValue());
        }
        //metadata.set(Task.METADATA_NAME_KEY, getApplicationName());
        return metadata;
    }

    @Override
    protected String isInputValid() {
        if (jTextFieldApplicationName.getText().length() == 0) {
            return "Enter the application name";
        } // TODO fix that?
        /*else if (!VerifyName.correct(jTextFieldApplicationName.getText())) {
            return VerifyName.ERROR_MESSAGE;
        }*/
        return null;
    }

    @Override
    protected JComponent getDefaultComponent() {
        return jTextFieldApplicationName;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldApplicationName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        messageLabel = buildMessageLabel()
        ;
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelAdditionalMetadata = new javax.swing.JPanel();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(NewApplicationPanel.class, "NewApplicationPanel.jLabel1.text")); // NOI18N

        jTextFieldApplicationName.setText(org.openide.util.NbBundle.getMessage(NewApplicationPanel.class, "NewApplicationPanel.jTextFieldApplicationName.text")); // NOI18N
        jTextFieldApplicationName.setToolTipText(org.openide.util.NbBundle.getMessage(NewApplicationPanel.class, "NewApplicationPanel.jTextFieldApplicationName.toolTipText")); // NOI18N

        jButton2.setText(org.openide.util.NbBundle.getMessage(NewApplicationPanel.class, "NewApplicationPanel.jButton2.text")); // NOI18N
        jButton2.setToolTipText(org.openide.util.NbBundle.getMessage(NewApplicationPanel.class, "NewApplicationPanel.jButton2.toolTipText")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        messageLabel.setText(org.openide.util.NbBundle.getMessage(NewApplicationPanel.class, "NewApplicationPanel.messageLabel.text")); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(NewApplicationPanel.class, "NewApplicationPanel.jScrollPane1.border.title"))); // NOI18N

        jPanelAdditionalMetadata.setBorder(null);
        jPanelAdditionalMetadata.setLayout(new javax.swing.BoxLayout(jPanelAdditionalMetadata, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(jPanelAdditionalMetadata);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApplicationName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApplicationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        jPanelAdditionalMetadata.add(
                new OneMetadataPanel("", "", false, true));
        this.revalidate();
    }//GEN-LAST:event_addActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAdditionalMetadata;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldApplicationName;
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables
}
