/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NetLogoTaskPanelUI.java
 *
 * Created on 21 avr. 2011, 11:18:10
 */
package org.openmole.ide.plugin.task.netlogo;

import javax.swing.JFileChooser;
import org.openmole.ide.core.properties.ITaskPanelUI;
import org.openmole.ide.core.properties.ITaskDataUI;
import org.openmole.ide.core.properties.DataUI;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mathieu
 */
public class NetLogoTaskPanelUI extends JPanel implements ITaskPanelUI {

    /** Creates new form NetLogoTaskPanelUI */
    public NetLogoTaskPanelUI(NetLogoTaskDataUI pud) {
        initComponents();
        nlogoTextField.setText(pud.nlogoPath());
        workspaceTextField.setText(pud.workspacePath());
        launchingCommandTextArea.setText(pud.lauchingCommands());
    }

    public ITaskDataUI saveContent(String name) {
        return new NetLogoTaskDataUI(name,  workspaceTextField.getText(), nlogoTextField.getText(), launchingCommandTextArea.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        launchingCommandTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        nlogoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nlogoBrowseButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        workspaceTextField = new javax.swing.JTextField();
        workspaceBrowseButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 222));

        launchingCommandTextArea.setColumns(20);
        launchingCommandTextArea.setRows(5);
        jScrollPane1.setViewportView(launchingCommandTextArea);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(NetLogoTaskPanelUI.class, "NetLogoTaskPanelUI.jLabel1.text")); // NOI18N

        nlogoTextField.setText(org.openide.util.NbBundle.getMessage(NetLogoTaskPanelUI.class, "NetLogoTaskPanelUI.nlogoTextField.text")); // NOI18N
        nlogoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nlogoTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(NetLogoTaskPanelUI.class, "NetLogoTaskPanelUI.jLabel2.text")); // NOI18N

        nlogoBrowseButton.setText(org.openide.util.NbBundle.getMessage(NetLogoTaskPanelUI.class, "NetLogoTaskPanelUI.nlogoBrowseButton.text")); // NOI18N
        nlogoBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nlogoBrowseButtonActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(NetLogoTaskPanelUI.class, "NetLogoTaskPanelUI.jLabel3.text")); // NOI18N

        workspaceTextField.setText(org.openide.util.NbBundle.getMessage(NetLogoTaskPanelUI.class, "NetLogoTaskPanelUI.workspaceTextField.text")); // NOI18N
        workspaceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workspaceTextFieldActionPerformed(evt);
            }
        });

        workspaceBrowseButton.setText(org.openide.util.NbBundle.getMessage(NetLogoTaskPanelUI.class, "NetLogoTaskPanelUI.workspaceBrowseButton.text")); // NOI18N
        workspaceBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workspaceBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(workspaceTextField)
                                    .addComponent(nlogoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(workspaceBrowseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nlogoBrowseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workspaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workspaceBrowseButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nlogoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nlogoBrowseButton)))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nlogoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nlogoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nlogoTextFieldActionPerformed

    private void workspaceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workspaceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workspaceTextFieldActionPerformed

    private void workspaceBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workspaceBrowseButtonActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Select your workspace directory");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            workspaceTextField.setText(fc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_workspaceBrowseButtonActionPerformed

    private void nlogoBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nlogoBrowseButtonActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Select your nlogo file");
        fc.setFileFilter(new FileNameExtensionFilter("Netlogo files", "nlogo"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            nlogoTextField.setText(fc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_nlogoBrowseButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea launchingCommandTextArea;
    private javax.swing.JButton nlogoBrowseButton;
    private javax.swing.JTextField nlogoTextField;
    private javax.swing.JButton workspaceBrowseButton;
    private javax.swing.JTextField workspaceTextField;
    // End of variables declaration//GEN-END:variables
}
