#!/bin/bash

CURDIR=$PWD
LOCATION=`dirname $0`

cd $LOCATION

nohup sh dbserver/bin/openmole-dbserver &

MEM="1G"

FLAG=""

JVMVERSION=`java -version 2>&1 | tail -1 -`

case "$JVMVERSION" in
  *64-Bit*) FLAG="-XX:+UseCompressedOops";;
esac

CONFIGDIR=$RANDOM

rm -Rf ./configuration/org*
rm ./configuration/*.log
java -Dosgi.locking=none -Dosgi.classloader.singleThreadLoads=true  -Dosgi.configuration.area=${CONFIGDIR} -splash:splashscreen.png -Xmx${MEM} $FLAG -XX:MaxPermSize=128M -XX:+UseParallelGC \
     -jar ./plugins/org.eclipse.equinox.launcher.jar \
     -cp ./openmole-plugins -gp ./openmole-plugins-gui "$@"
#cat $LOCATION/configuration/*.log

rm -rf ${CONFIGDIR} 

cd $CURDIR

