/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PropertyPanel.java
 *
 * Created on 20 avr. 2011, 11:20:26
 */
package org.openmole.ide.core;

import java.util.Iterator;
import org.openide.util.Lookup;
import org.openmole.ide.core.properties.IFactoryUI;
import org.openmole.ide.core.properties.ISamplingFactoryUI;
import org.openmole.ide.core.properties.ITaskFactoryUI;

/**
 *
 * @author mathieu
 */
public class PropertyPanel extends javax.swing.JPanel {

    /** Creates new form PropertyPanel */
    public PropertyPanel() {
        initComponents();
    }

    private void fillTypeComboBox(Class typeClass) {
        typeComboBox.removeAllItems();
        for (Iterator it = Lookup.getDefault().lookupAll(typeClass).iterator(); it.hasNext();) {
            typeComboBox.addItem(((IFactoryUI) it.next()).coreClass().getSimpleName());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        prototypeToggleButton = new javax.swing.JToggleButton();
        TaskToogleButton = new javax.swing.JToggleButton();
        SamplingToogleButton = new javax.swing.JToggleButton();
        EnvironmentToogleButton = new javax.swing.JToggleButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.jTextField1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.jLabel2.text")); // NOI18N

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        prototypeToggleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.prototypeToggleButton.text")); // NOI18N
        prototypeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prototypeToggleButtonActionPerformed(evt);
            }
        });

        TaskToogleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.TaskToogleButton.text")); // NOI18N
        TaskToogleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskToogleButtonActionPerformed(evt);
            }
        });

        SamplingToogleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.SamplingToogleButton.text")); // NOI18N
        SamplingToogleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamplingToogleButtonActionPerformed(evt);
            }
        });

        EnvironmentToogleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.EnvironmentToogleButton.text")); // NOI18N
        EnvironmentToogleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvironmentToogleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prototypeToggleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TaskToogleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SamplingToogleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnvironmentToogleButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EnvironmentToogleButton, SamplingToogleButton, TaskToogleButton, prototypeToggleButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SamplingToogleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaskToogleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnvironmentToogleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prototypeToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prototypeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prototypeToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prototypeToggleButtonActionPerformed

    private void TaskToogleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskToogleButtonActionPerformed
                                                
        fillTypeComboBox(ITaskFactoryUI.class);
    }//GEN-LAST:event_TaskToogleButtonActionPerformed

    private void SamplingToogleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamplingToogleButtonActionPerformed
        fillTypeComboBox(ISamplingFactoryUI.class);
    }//GEN-LAST:event_SamplingToogleButtonActionPerformed

    private void EnvironmentToogleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvironmentToogleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnvironmentToogleButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton EnvironmentToogleButton;
    private javax.swing.JToggleButton SamplingToogleButton;
    private javax.swing.JToggleButton TaskToogleButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton prototypeToggleButton;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables
}
