/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PropertyPanel.java
 *
 * Created on 20 avr. 2011, 11:20:26
 */
package org.openmole.ide.core;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Iterator;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.plaf.basic.BasicComboBoxRenderer;
import org.openide.util.Lookup;
import org.openmole.ide.core.properties.PanelUI;
import org.openmole.ide.core.properties.IFactoryUI;
import org.openmole.ide.core.properties.ISamplingFactoryUI;
import org.openmole.ide.core.properties.ITaskFactoryUI;

/**
 *
 * @author mathieu
 */
public class PropertyPanel extends javax.swing.JPanel {

    EntityPropertyTopComponent entityComponent;

    /** Creates new form PropertyPanel */
    public PropertyPanel(EntityPropertyTopComponent ec) {
        entityComponent = ec;
        initComponents();

        typeComboBox.removeAllItems();
        typeComboBox.setRenderer(new ItemRenderer());
        typeComboBox.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent ie) {
                System.out.println(((IFactoryUI) typeComboBox.getSelectedItem()).coreClass() + " PANEL :: " + ((IFactoryUI) typeComboBox.getSelectedItem()).panel());
                
                if (entityComponent.getComponents().length == 2) {
                remove(1);
            }
            entityComponent.add((Component)(((IFactoryUI) typeComboBox.getSelectedItem()).panel()));
            }
        });

        ButtonGroup group = new ButtonGroup();
        group.add(prototypeToggleButton);
        group.add(taskToogleButton);
        group.add(samplingToogleButton);
        group.add(environmentToogleButton);

        edit(false);
        taskToogleButton.setSelected(true);
    }

    private void fillTypeComboBox(Class typeClass) {
        typeComboBox.removeAllItems();

        for (Iterator it = Lookup.getDefault().lookupAll(typeClass).iterator(); it.hasNext();) {
            //  typeComboBox.addItem(((IFactoryUI) it.next()).coreClass().getSimpleName());
            typeComboBox.addItem((IFactoryUI) it.next());
            // typeComboBox.addItem(((IFactoryUI) it.next()).coreClass().getSimpleName());
        }
    }

    private void edit(Boolean b) {
        typeComboBox.setEnabled(b);
        nameTextField.setEnabled(b);
        editToggleButton.setText(b ? "Save" : "Edit");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        prototypeToggleButton = new javax.swing.JToggleButton();
        taskToogleButton = new javax.swing.JToggleButton();
        samplingToogleButton = new javax.swing.JToggleButton();
        environmentToogleButton = new javax.swing.JToggleButton();
        newToggleButton = new javax.swing.JToggleButton();
        editToggleButton = new javax.swing.JToggleButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.jLabel1.text")); // NOI18N

        nameTextField.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.nameTextField.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.jLabel2.text")); // NOI18N

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        prototypeToggleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.prototypeToggleButton.text")); // NOI18N
        prototypeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prototypeToggleButtonActionPerformed(evt);
            }
        });

        taskToogleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.taskToogleButton.text")); // NOI18N
        taskToogleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskToogleButtonActionPerformed(evt);
            }
        });

        samplingToogleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.samplingToogleButton.text")); // NOI18N
        samplingToogleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samplingToogleButtonActionPerformed(evt);
            }
        });

        environmentToogleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.environmentToogleButton.text")); // NOI18N
        environmentToogleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                environmentToogleButtonActionPerformed(evt);
            }
        });

        newToggleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.newToggleButton.text")); // NOI18N
        newToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newToggleButtonActionPerformed(evt);
            }
        });

        editToggleButton.setText(org.openide.util.NbBundle.getMessage(PropertyPanel.class, "PropertyPanel.editToggleButton.text")); // NOI18N
        editToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prototypeToggleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taskToogleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(samplingToogleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(typeComboBox, 0, 302, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(environmentToogleButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {environmentToogleButton, prototypeToggleButton, samplingToogleButton, taskToogleButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editToggleButton, newToggleButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(samplingToogleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(environmentToogleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(taskToogleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prototypeToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prototypeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prototypeToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prototypeToggleButtonActionPerformed

    private void taskToogleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskToogleButtonActionPerformed

        fillTypeComboBox(ITaskFactoryUI.class);
    }//GEN-LAST:event_taskToogleButtonActionPerformed

    private void samplingToogleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samplingToogleButtonActionPerformed
        fillTypeComboBox(ISamplingFactoryUI.class);
    }//GEN-LAST:event_samplingToogleButtonActionPerformed

    private void environmentToogleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_environmentToogleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_environmentToogleButtonActionPerformed

    private void newToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newToggleButtonActionPerformed

    private void editToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editToggleButtonActionPerformed
        edit(editToggleButton.isSelected());
    }//GEN-LAST:event_editToggleButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton editToggleButton;
    private javax.swing.JToggleButton environmentToogleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JToggleButton newToggleButton;
    private javax.swing.JToggleButton prototypeToggleButton;
    private javax.swing.JToggleButton samplingToogleButton;
    private javax.swing.JToggleButton taskToogleButton;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables

    class ItemRenderer extends BasicComboBoxRenderer {

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value != null) {
                IFactoryUI f = (IFactoryUI) value;
                setText(f.coreClass().getSimpleName());
            }
            return this;
        }
    }
}
