#!/bin/bash

CURDIR=$PWD
LOCATION=`dirname $0`

(nohup sh $LOCATION/dbserver/bin/openmole-dbserver >/dev/null &) 2>/dev/null

MEM="1G"

FLAG=""

JVMVERSION=`java -version 2>&1 | tail -1 -`

case "$JVMVERSION" in
  *64-Bit*) FLAG="-XX:+UseCompressedOops";;
esac

SPLASHSCREEN="-splash:$LOCATION/splashscreen.png"

for ARG in $@
do
  if [[ $ARG == "-c" || $ARG == "-ws" ]]; then SPLASHSCREEN=""; fi
done


CONFIGDIR=$LOCATION/$RANDOM


java -Dosgi.locking=none -Dopenmole.location=${LOCATION} -Dosgi.classloader.singleThreadLoads=true  -Dosgi.configuration.area=${CONFIGDIR} $SPLASHSCREEN -Xmx${MEM} $FLAG -XX:MaxPermSize=128M -XX:+UseParallelGC \
     -jar $LOCATION/plugins/org.eclipse.equinox.launcher.jar \
     -cp $LOCATION/openmole-plugins -gp $LOCATION/openmole-plugins-gui "$@"

rm -rf ${CONFIGDIR} 

