#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Please supply the target path"
  exit 1
fi

TARGET=$1

if [ -e ${TARGET} ]; then
  echo "Destination directory \"$TARGET\" already exists"
  exit 1
fi

mkdir -p "${TARGET}" && \
  sbt "buildSite --target \"${TARGET}\"" && \
  (git clone https://gitlab.openmole.org/narduin/refonte-hp "${TARGET}/build_hp" && cd "${TARGET}/build_hp" && npm clean && rm -rf dist/ && npm install && npm run build && cp -r dist/index.html ${TARGET} && rm -rf "${TARGET}/build_hp") && \
  sbt "project openmole" clean "set (tarPath := new File(\"${TARGET}/openmole.tar.gz\"))" tar && \
  #sbt "project org-openmole-daemon" clean "set (tarPath := new File(\"${TARGET}/daemon.tar.gz\"))" tar && \
  rm -rf "${TARGET}/api" && \
  #sbt "project api" "set (crossTarget in api) := new File(\"${TARGET}\")" unidoc && \
  #mv "${TARGET}/unidoc" "${TARGET}/api" && \
  sbt ";project marketindex; cloneMarket; run --target \"${TARGET}/market\" --market \"./bin/org.openmole.marketindex/target/openmole-market/\"" && \
  sbt "project org-openmole-modules" assemble && \
  ./bin/org.openmole.modules/target/assemble/modules --target "${TARGET}/modules" && \
  echo "the website was generated in file://${TARGET}/index.html"

